// <auto-generated />
using System;
using FAS.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAS.Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251001022831_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAS.Model.Models.AdminActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AdminAct__3213E83F7A9CAFA1");

                    b.HasIndex(new[] { "Id" }, "UQ__AdminAct__3213E83E42988AEA")
                        .IsUnique();

                    b.ToTable("AdminActionLog", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Award__3213E83F3BDEEB17");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Id" }, "UQ__Award__3213E83ED73AD8EE")
                        .IsUnique();

                    b.ToTable("Award", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.AwardCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentCategory")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__AwardCat__3213E83FD3F90307");

                    b.HasIndex("ParentCategory");

                    b.HasIndex(new[] { "Id" }, "UQ__AwardCat__3213E83EAAAAD18F")
                        .IsUnique();

                    b.ToTable("AwardCategory", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.AwardPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__AwardPer__3213E83F270BACB7");

                    b.HasIndex(new[] { "Id" }, "UQ__AwardPer__3213E83E585E425B")
                        .IsUnique();

                    b.ToTable("AwardPeriod", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Blog__3213E83F141A6B93");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Id" }, "UQ__Blog__3213E83E7D05D484")
                        .IsUnique();

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.CommentNominee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__CommentN__3213E83F5FD7C052");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "Id" }, "UQ__CommentN__3213E83ECA8964CD")
                        .IsUnique();

                    b.ToTable("CommentNominee", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.CouncilMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__CouncilM__3213E83FD0498D1E");

                    b.HasIndex(new[] { "Id" }, "UQ__CouncilM__3213E83E0EBE96D0")
                        .IsUnique();

                    b.ToTable("CouncilMember", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CouncilMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CriteriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Evaluati__3213E83F965D3AFC");

                    b.HasIndex("CouncilMemberId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("NomineeId");

                    b.HasIndex(new[] { "Id" }, "UQ__Evaluati__3213E83E49B00C01")
                        .IsUnique();

                    b.ToTable("Evaluation", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.EvaluationCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AwardCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("award_category_id");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Evaluati__3213E83FB305C922");

                    b.HasIndex("AwardCategoryId");

                    b.HasIndex(new[] { "Id" }, "UQ__Evaluati__3213E83EF651AA92")
                        .IsUnique();

                    b.ToTable("EvaluationCriteria");
                });

            modelBuilder.Entity("FAS.Model.Models.NominateActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Nominate__3213E83F057877EB");

                    b.HasIndex("NomineeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Id" }, "UQ__Nominate__3213E83E5828620A")
                        .IsUnique();

                    b.ToTable("NominateActionLog", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.Nominee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelatedInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Summary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Nominee__3213E83F2715F9C0");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubmittedById");

                    b.HasIndex(new[] { "Id" }, "UQ__Nominee__3213E83E538B9919")
                        .IsUnique();

                    b.ToTable("Nominee", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3213E83F6F4D47AF");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TargetUser");

                    b.HasIndex(new[] { "Id" }, "UQ__Notifica__3213E83E427741B6")
                        .IsUnique();

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FapId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte?>("Role")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("VoteStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F4AB77DCF");

                    b.HasIndex(new[] { "Id" }, "UQ__User__3213E83E347A65C7")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NomineeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Vote__3213E83FD93E9124");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NomineeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Id" }, "UQ__Vote__3213E83E1BC43205")
                        .IsUnique();

                    b.ToTable("Vote", (string)null);
                });

            modelBuilder.Entity("FAS.Model.Models.AdminActionLog", b =>
                {
                    b.HasOne("FAS.Model.Models.User", "IdNavigation")
                        .WithOne("AdminActionLog")
                        .HasForeignKey("FAS.Model.Models.AdminActionLog", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__AdminActionL__id__60A75C0F");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.Award", b =>
                {
                    b.HasOne("FAS.Model.Models.AwardCategory", "Category")
                        .WithMany("Awards")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Award__CategoryI__5DCAEF64");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FAS.Model.Models.AwardCategory", b =>
                {
                    b.HasOne("FAS.Model.Models.AwardCategory", "ParentCategoryNavigation")
                        .WithMany("InverseParentCategoryNavigation")
                        .HasForeignKey("ParentCategory")
                        .HasConstraintName("FK__AwardCate__Paren__6383C8BA");

                    b.Navigation("ParentCategoryNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.AwardPeriod", b =>
                {
                    b.HasOne("FAS.Model.Models.Award", "IdNavigation")
                        .WithOne("AwardPeriod")
                        .HasForeignKey("FAS.Model.Models.AwardPeriod", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__AwardPeriod__id__5EBF139D");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.Blog", b =>
                {
                    b.HasOne("FAS.Model.Models.AdminActionLog", "CreatedByNavigation")
                        .WithMany("Blogs")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Blog__CreatedBy__6A30C649");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.CommentNominee", b =>
                {
                    b.HasOne("FAS.Model.Models.AdminActionLog", "CreatedByNavigation")
                        .WithMany("CommentNominees")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__CommentNo__Creat__6C190EBB");

                    b.HasOne("FAS.Model.Models.Nominee", "IdNavigation")
                        .WithOne("CommentNominee")
                        .HasForeignKey("FAS.Model.Models.CommentNominee", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__CommentNomin__id__6B24EA82");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.CouncilMember", b =>
                {
                    b.HasOne("FAS.Model.Models.User", "IdNavigation")
                        .WithOne("CouncilMember")
                        .HasForeignKey("FAS.Model.Models.CouncilMember", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__CouncilMembe__id__66603565");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.Evaluation", b =>
                {
                    b.HasOne("FAS.Model.Models.CouncilMember", "CouncilMember")
                        .WithMany("Evaluations")
                        .HasForeignKey("CouncilMemberId")
                        .HasConstraintName("FK__Evaluatio__Counc__6754599E");

                    b.HasOne("FAS.Model.Models.EvaluationCriterion", "Criteria")
                        .WithMany("Evaluations")
                        .HasForeignKey("CriteriaId")
                        .HasConstraintName("FK__Evaluatio__Crite__68487DD7");

                    b.HasOne("FAS.Model.Models.Nominee", "Nominee")
                        .WithMany("Evaluations")
                        .HasForeignKey("NomineeId")
                        .HasConstraintName("FK__Evaluatio__Nomin__693CA210");

                    b.Navigation("CouncilMember");

                    b.Navigation("Criteria");

                    b.Navigation("Nominee");
                });

            modelBuilder.Entity("FAS.Model.Models.EvaluationCriterion", b =>
                {
                    b.HasOne("FAS.Model.Models.AwardCategory", "AwardCategory")
                        .WithMany("EvaluationCriteria")
                        .HasForeignKey("AwardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EvaluationCriterion_AwardCategory");

                    b.Navigation("AwardCategory");
                });

            modelBuilder.Entity("FAS.Model.Models.NominateActionLog", b =>
                {
                    b.HasOne("FAS.Model.Models.Nominee", "Nominee")
                        .WithMany("NominateActionLogs")
                        .HasForeignKey("NomineeId")
                        .HasConstraintName("FK__NominateA__Nomin__6EF57B66");

                    b.HasOne("FAS.Model.Models.User", "User")
                        .WithMany("NominateActionLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__NominateA__UserI__6FE99F9F");

                    b.Navigation("Nominee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FAS.Model.Models.Nominee", b =>
                {
                    b.HasOne("FAS.Model.Models.AwardCategory", "Category")
                        .WithMany("Nominees")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Nominee__Categor__656C112C");

                    b.HasOne("FAS.Model.Models.User", "SubmittedBy")
                        .WithMany("Nominees")
                        .HasForeignKey("SubmittedById")
                        .HasConstraintName("FK__Nominee__Submitt__5FB337D6");

                    b.Navigation("Category");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("FAS.Model.Models.Notification", b =>
                {
                    b.HasOne("FAS.Model.Models.AdminActionLog", "CreatedByNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK__Notificat__Creat__6D0D32F4");

                    b.HasOne("FAS.Model.Models.User", "TargetUserNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetUser")
                        .HasConstraintName("FK__Notificat__Targe__6E01572D");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("TargetUserNavigation");
                });

            modelBuilder.Entity("FAS.Model.Models.Vote", b =>
                {
                    b.HasOne("FAS.Model.Models.AwardCategory", "Category")
                        .WithMany("Votes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Vote__CategoryId__6477ECF3");

                    b.HasOne("FAS.Model.Models.Nominee", "Nominee")
                        .WithMany("Votes")
                        .HasForeignKey("NomineeId")
                        .HasConstraintName("FK__Vote__NomineeId__628FA481");

                    b.HasOne("FAS.Model.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Vote__UserId__619B8048");

                    b.Navigation("Category");

                    b.Navigation("Nominee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FAS.Model.Models.AdminActionLog", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("CommentNominees");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("FAS.Model.Models.Award", b =>
                {
                    b.Navigation("AwardPeriod");
                });

            modelBuilder.Entity("FAS.Model.Models.AwardCategory", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("EvaluationCriteria");

                    b.Navigation("InverseParentCategoryNavigation");

                    b.Navigation("Nominees");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FAS.Model.Models.CouncilMember", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("FAS.Model.Models.EvaluationCriterion", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("FAS.Model.Models.Nominee", b =>
                {
                    b.Navigation("CommentNominee");

                    b.Navigation("Evaluations");

                    b.Navigation("NominateActionLogs");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("FAS.Model.Models.User", b =>
                {
                    b.Navigation("AdminActionLog");

                    b.Navigation("CouncilMember");

                    b.Navigation("NominateActionLogs");

                    b.Navigation("Nominees");

                    b.Navigation("Notifications");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
